### PR TITLE
Unreachable chips

### PR DESCRIPTION
**Pull request by rowleya**
Makes it possible to detect and map out chips that can't be used due to down links.

### CODE REVIEW

**Comment by alan-stokes** [comment]
going to ask a stupid question. but given the spinnman exploration of the machine works by communicating down links and cores. How do you end up with a real machine which has a unreachable chip?

**Comment by rowleya** [comment]
SpiNNMan exploration doesn't do this any more; the machine has already done some amount of this and we use this information.  In any case, we did end up with a real machine in this exact state!  I think it is because the links out seem to work, whereas the links in fail, so the chip has spoken to the surrounding chips, but just hasn't been spoken to...

**Comment by rowleya** [comment]
OK, so I have checked this and it is a bit odd.  We now use the P2P table to tell us what chips exist.  This is fine, except that we then ask the chip itself for its chip information.  If the chip fails to give us this information, we would consider it not working.  That the chip is in the P2P table makes sense; the chip has sent out messages to neighbouring chips so this only requires outgoing links.  The interesting bit is that we then must have spoken to the chip i.e. sent it P2P messages to get information from it.  This has worked, but the links themselves are considered down!  There is an oddity here certainly...

**Comment by alan-stokes** [comment]
so basically, this is all a sticky plaster over dodgy machine detection again. i can live with that.

**Comment by rowleya** [comment]
Pretty much!

**Pull request merged**
