### PR TITLE
turn on github actions

### PR DESCRIPTION
**Pull request by Christian-B**
The c actions is a demo to show multiple yml work.

### CODE REVIEW

**Review by andrewgait — CHANGES_REQUESTED** [review]
Looks fine to me so far, a couple of observations:

1) we probably shouldn't use the name TRAVIS_BRANCH, it should be GITHUB_BRANCH or something like that I think?
2) the SpiNNUtils branch I was working on now also has sphinx and coveralls added to it, so this could also be added here, see https://github.com/SpiNNakerManchester/SpiNNUtils/pull/123/files

**Comment by dkfellows** [comment]
> we probably shouldn't use the name `TRAVIS_BRANCH`, it should be `GITHUB_BRANCH` or something like that I think?

The name was originally only used in our CI scripts because that environment variable was explicitly already made available on Travis. Nothing more.

**Comment by andrewgait** [comment]
OK, this is passing now with the merged doc changes.  I think we can probably turn off the pull_request actions as well, as we were working with just push on Travis before this.

**Review by andrewgait — APPROVED** [review]

**Comment by dkfellows** [comment]
Why do we have both “Python Actions” and “Python Actions Extended”?

**Comment by dkfellows** [comment]
Important matters: [badges!](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge)

**Review by dkfellows — APPROVED** [review]

**Pull request merged**
