### PR TITLE
Fix for calling this function across multiple boards

### PR DESCRIPTION
**Pull request by andrewgait**
This was causing me problems when running MCMC over more than 1 board via spalloc.

There should probably be a unit or integration test to check this works properly as well; happy to write it but will have to be next week now...

### CODE REVIEW

**Comment by alan-stokes** [comment]
i don't think this is a valid fix. my question is what error is this trying to fix?  logic below, if my logic is flawed, please explain:

1. if on a 48 chip board, the etherent chip will be 0,0 and those gaps will work regardless of Ethernet chip ids or not.
2. if there's a 4 chip board, it'll never hit those sizes.
3. if there's a multiboard setup, those gaps should be filled in (def in a wrap around), and if not, they wont 100% be the ones from the standard 48 chip size. the ids will all be ascending order from a given point, and using the Ethernet chip ids as a basis seems a sound premise. So chips on board 3 may be from 4,8 onward, and therefore comparing them as if they are say 0,4 seems a odd thing to do.

**Comment by rowleya** [comment]
Have a look at the surrounding code.  Basically, any board which is not the first board in a multiboard arrangements will have more than 48 chips unless this fix is applied...

**Comment by alan-stokes** [comment]
having discussed with rowley. we both were right and wrong, we found a missing component. If you have a wrap around multi board system, such as shown here: https://drive.google.com/drive/folders/0B9312BuJXntlb2w0OGx1OVU5cmc
Then this code with only produce the none wrap around components. There needs to be a cast with max chipx and max chip y to ensure it checks that chips wrapped still exist. 

I note that you do need to check chip_x and chip-y given the mismatch between gaps, so good work there, but jsut not 100% covered yet. 

It implies there's a lot of unit/intergrationt tests missing to verify this logic code is solid.

**Comment by andrewgait** [comment]
Updated to deal with the wrap_around case - I think.  Tests still to come...

**Pull request merged**
