### PR TITLE
Make import statements use PEP 328 better

### PR DESCRIPTION
**Pull request by dkfellows**
https://www.python.org/dev/peps/pep-0328/#rationale-for-parentheses

### CODE REVIEW

**Comment by alan-stokes** [comment]
dot imports. yuck. when did those slip in?

**Comment by Christian-B** [comment]
"dot imports. yuck. when did those slip in?"

Oh only 11 months ago but nice to see you finally noticed Alan.

**Comment by dkfellows** [comment]
This PR isn't about changing those; get your own PR if you feel like trying to fight that again. It's about getting rid of backslashes and putting external modules (_especially_ those from Python itself) first.

**Comment by alan-stokes** [comment]
11 months ago....... well when ya slip stuff in without full review ;-)
anyhow, the rest look ok, id like to test it on a pycharm setup before rubbering, but thats probematic right now. lol

**Pull request merged**
