### PR TITLE
Accurate vm

### PR DESCRIPTION
**Pull request by Christian-B**
If a virtual machine is requested WITHOUT specifying n_cpus_per_chip  (or passing in None) a Machine is created with a split between 18 and 17 core chips as is typical in the 1,000,000 core machine.

Builds on: https://github.com/SpiNNakerManchester/SpiNNMachine/pull/124
So must be done AFTER that PR group.

Currently no matching PR to get the MaxMachineGenerators to use this but there probably should be one.

### CODE REVIEW

**Comment by alan-stokes** [comment]
why do we care about this? typical and the same are not the same.

**Comment by Christian-B** [comment]
The current system is to create virtual machines where all chips have 18 cores which is too many cores or 17 which is too few.

This give as good an estimate of the real machine as is practical.

The idea of getting the actual real machine to do estimates is a none starter unless the job is so big it needs the whole machine.  The reason is that even with a description of the whole machine you would not know which part of the machine to estimate against.  Even if you could ask for a specific bit of the machine this would be a bad idea as jobs could needlessly hang just because they choose the same bit as another possibly long running job.

**Comment by alan-stokes** [comment]
the issue i have. is your solution is also a none starter for basically the same reasons. how many boards have that exact layout? whats the distribution from worst to best? heck, by using yours, do you end up over or under estimating the total number of cores on the big machine? Id be very very surprised if you hit the correct number. 

so yours is a estimate fudge on a estimate fudge. Least having the real machine means your testing against a REAL thing, a thing you COULD get. Yes you might not get the given chips you originally partitioned for, but the theory is that by having the real machine, you cant be hung up with fudge factors, which is what we currently have. 

by making the spalloc request way way better than just n cores / n boards. you can get spalloc to give you a machine which REGARDLESS of the actual chips given. matches your requirements. 

THIS DOES NOT DO THAT

**Comment by alan-stokes** [comment]
my simple maths says yours has 40 chips with 18 cores, and thus 8 with 17 cores. 

that's 856 cores per board. which is 1027200 cores for the big machine. Im sure we're around 1010,000 so you're overestimating. maybe @lplana can give the exact numbers of the BEST boot we've had, and i bet it doesn't hit that value.

**Comment by rowleya** [comment]
We have had some discussion about this.  We know that *every* 48-chip board has specific chips which are known to at best have 17 working cores.  This is specified at the board level, so having an initial setup with those chips as 17 core chips and the rest as 18 is better than what we have now, even if it doesn't solve all our problems.  And better than what we have now is worth adding.

**Comment by alan-stokes** [comment]
a sticky plaster over a sticky plaster. how about we solve it properly instead. your overestimating. which means anything that should need all the machine is never going to work. coz its got more core to play with than it really has

**Pull request merged**
